CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Amenities" (
        "AmenityId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Amenities" PRIMARY KEY ("AmenityId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "DichVus" (
        "DichVuId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_DichVus" PRIMARY KEY ("DichVuId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleName" text NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "RoomTypes" (
        "RoomTypeId" integer GENERATED BY DEFAULT AS IDENTITY,
        "TypeName" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_RoomTypes" PRIMARY KEY ("RoomTypeId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Users" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "FullName" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "PhoneNumber" text NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "RoomType_DichVus" (
        "RoomTypeId" integer NOT NULL,
        "DichVuId" integer NOT NULL,
        CONSTRAINT "PK_RoomType_DichVus" PRIMARY KEY ("RoomTypeId", "DichVuId"),
        CONSTRAINT "FK_RoomType_DichVus_DichVus_DichVuId" FOREIGN KEY ("DichVuId") REFERENCES "DichVus" ("DichVuId") ON DELETE CASCADE,
        CONSTRAINT "FK_RoomType_DichVus_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES "RoomTypes" ("RoomTypeId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "IdentityDocuments" (
        "IdentityDocumentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "CCCDNumber" text NOT NULL,
        "Status" text NOT NULL,
        "ReviewedBy" integer,
        CONSTRAINT "PK_IdentityDocuments" PRIMARY KEY ("IdentityDocumentId"),
        CONSTRAINT "FK_IdentityDocuments_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_IdentityDocuments_Users_ReviewedBy" FOREIGN KEY ("ReviewedBy") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "KhuTros" (
        "KhuTroId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" integer NOT NULL,
        "PropertyName" text NOT NULL,
        "AddressText" text NOT NULL,
        "Ward" text NOT NULL,
        "District" text NOT NULL,
        "City" text NOT NULL,
        "Latitude" numeric(18,2) NOT NULL,
        "Longitude" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_KhuTros" PRIMARY KEY ("KhuTroId"),
        CONSTRAINT "FK_KhuTros_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Title" text NOT NULL,
        "Type" text NOT NULL,
        "IsRead" boolean NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
        CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Rooms" (
        "RoomId" integer GENERATED BY DEFAULT AS IDENTITY,
        "KhuTroId" integer NOT NULL,
        "RoomTypeId" integer NOT NULL,
        "RoomCode" text NOT NULL,
        "AreaSqm" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("RoomId"),
        CONSTRAINT "FK_Rooms_KhuTros_KhuTroId" FOREIGN KEY ("KhuTroId") REFERENCES "KhuTros" ("KhuTroId") ON DELETE CASCADE,
        CONSTRAINT "FK_Rooms_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES "RoomTypes" ("RoomTypeId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Bookings" (
        "BookingId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        "DepositAmount" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        "ExpiryDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("BookingId"),
        CONSTRAINT "FK_Bookings_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("RoomId") ON DELETE CASCADE,
        CONSTRAINT "FK_Bookings_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Equipments" (
        "EquipmentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "Name" text NOT NULL,
        "InstallDate" date NOT NULL,
        "WarrantyExpiry" date NOT NULL,
        "Supplier" text NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Equipments" PRIMARY KEY ("EquipmentId"),
        CONSTRAINT "FK_Equipments_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("RoomId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "RoomAmenities" (
        "RoomId" integer NOT NULL,
        "AmenityId" integer NOT NULL,
        CONSTRAINT "PK_RoomAmenities" PRIMARY KEY ("RoomId", "AmenityId"),
        CONSTRAINT "FK_RoomAmenities_Amenities_AmenityId" FOREIGN KEY ("AmenityId") REFERENCES "Amenities" ("AmenityId") ON DELETE CASCADE,
        CONSTRAINT "FK_RoomAmenities_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("RoomId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "RoomImages" (
        "RoomImageId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "ImageUrl" text NOT NULL,
        "IsPrimary" boolean NOT NULL,
        CONSTRAINT "PK_RoomImages" PRIMARY KEY ("RoomImageId"),
        CONSTRAINT "FK_RoomImages_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("RoomId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Contracts" (
        "ContractId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        "BookingId" integer,
        "ProcessedByStaffId" integer,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "MonthlyRent" numeric(18,2) NOT NULL,
        "DepositAmount" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Contracts" PRIMARY KEY ("ContractId"),
        CONSTRAINT "FK_Contracts_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("BookingId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Contracts_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("RoomId") ON DELETE CASCADE,
        CONSTRAINT "FK_Contracts_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Contracts_Users_ProcessedByStaffId" FOREIGN KEY ("ProcessedByStaffId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Invoices" (
        "InvoiceId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContractId" integer NOT NULL,
        "InvoiceMonth" date NOT NULL,
        "DueDate" date NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Invoices" PRIMARY KEY ("InvoiceId"),
        CONSTRAINT "FK_Invoices_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "MaintenanceRequests" (
        "RequestId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContractId" integer NOT NULL,
        "EquipmentId" integer,
        "AssignedTo" integer,
        "Description" text NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_MaintenanceRequests" PRIMARY KEY ("RequestId"),
        CONSTRAINT "FK_MaintenanceRequests_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE CASCADE,
        CONSTRAINT "FK_MaintenanceRequests_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("EquipmentId"),
        CONSTRAINT "FK_MaintenanceRequests_Users_AssignedTo" FOREIGN KEY ("AssignedTo") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "UtilityReadings" (
        "ReadingId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContractId" integer NOT NULL,
        "ReadingMonth" date NOT NULL,
        "ElectricStart" numeric(18,2) NOT NULL,
        "ElectricEnd" numeric(18,2) NOT NULL,
        "WaterStart" numeric(18,2) NOT NULL,
        "WaterEnd" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_UtilityReadings" PRIMARY KEY ("ReadingId"),
        CONSTRAINT "FK_UtilityReadings_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "InvoiceDetails" (
        "InvoiceDetailId" integer GENERATED BY DEFAULT AS IDENTITY,
        "InvoiceId" integer NOT NULL,
        "ItemType" text NOT NULL,
        "Description" text NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_InvoiceDetails" PRIMARY KEY ("InvoiceDetailId"),
        CONSTRAINT "FK_InvoiceDetails_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("InvoiceId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "MaintenanceLogs" (
        "LogId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" integer NOT NULL,
        "OldStatus" text NOT NULL,
        "NewStatus" text NOT NULL,
        "ChangedBy" integer,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MaintenanceLogs" PRIMARY KEY ("LogId"),
        CONSTRAINT "FK_MaintenanceLogs_MaintenanceRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "MaintenanceRequests" ("RequestId") ON DELETE CASCADE,
        CONSTRAINT "FK_MaintenanceLogs_Users_ChangedBy" FOREIGN KEY ("ChangedBy") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "PaymentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "BookingId" integer,
        "ContractId" integer,
        "InvoiceId" integer,
        "ReadingId" integer,
        "Amount" numeric(18,2) NOT NULL,
        "PaymentMethod" text NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
        CONSTRAINT "FK_Payments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("BookingId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Payments_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Payments_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("InvoiceId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Payments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Payments_UtilityReadings_ReadingId" FOREIGN KEY ("ReadingId") REFERENCES "UtilityReadings" ("ReadingId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_CustomerId" ON "Bookings" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_RoomId" ON "Bookings" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Contracts_BookingId" ON "Contracts" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Contracts_CustomerId" ON "Contracts" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Contracts_ProcessedByStaffId" ON "Contracts" ("ProcessedByStaffId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Contracts_RoomId" ON "Contracts" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Equipments_RoomId" ON "Equipments" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_IdentityDocuments_CustomerId" ON "IdentityDocuments" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_IdentityDocuments_ReviewedBy" ON "IdentityDocuments" ("ReviewedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_InvoiceDetails_InvoiceId" ON "InvoiceDetails" ("InvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Invoices_ContractId" ON "Invoices" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_KhuTros_OwnerId" ON "KhuTros" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_MaintenanceLogs_ChangedBy" ON "MaintenanceLogs" ("ChangedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_MaintenanceLogs_RequestId" ON "MaintenanceLogs" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_MaintenanceRequests_AssignedTo" ON "MaintenanceRequests" ("AssignedTo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_MaintenanceRequests_ContractId" ON "MaintenanceRequests" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_MaintenanceRequests_EquipmentId" ON "MaintenanceRequests" ("EquipmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Payments_BookingId" ON "Payments" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Payments_ContractId" ON "Payments" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Payments_InvoiceId" ON "Payments" ("InvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Payments_ReadingId" ON "Payments" ("ReadingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Payments_UserId" ON "Payments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_RoomAmenities_AmenityId" ON "RoomAmenities" ("AmenityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_RoomImages_RoomId" ON "RoomImages" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Rooms_KhuTroId" ON "Rooms" ("KhuTroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Rooms_RoomTypeId" ON "Rooms" ("RoomTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_RoomType_DichVus_DichVuId" ON "RoomType_DichVus" ("DichVuId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    CREATE INDEX "IX_UtilityReadings_ContractId" ON "UtilityReadings" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003142421_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003142421_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    ALTER TABLE "Rooms" DROP CONSTRAINT "FK_Rooms_KhuTros_KhuTroId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    DROP TABLE "KhuTros";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    DROP TABLE "RoomType_DichVus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    DROP TABLE "DichVus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    ALTER TABLE "Rooms" RENAME COLUMN "KhuTroId" TO "PropertyId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    ALTER INDEX "IX_Rooms_KhuTroId" RENAME TO "IX_Rooms_PropertyId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    CREATE TABLE "Properties" (
        "PropertyId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" integer NOT NULL,
        "PropertyName" text NOT NULL,
        "AddressText" text NOT NULL,
        "Ward" text NOT NULL,
        "District" text NOT NULL,
        "City" text NOT NULL,
        "Latitude" numeric(18,2) NOT NULL,
        "Longitude" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_Properties" PRIMARY KEY ("PropertyId"),
        CONSTRAINT "FK_Properties_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    CREATE TABLE "Services" (
        "ServiceId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_Services" PRIMARY KEY ("ServiceId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    CREATE TABLE "RoomTypeServices" (
        "RoomTypeId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        CONSTRAINT "PK_RoomTypeServices" PRIMARY KEY ("RoomTypeId", "ServiceId"),
        CONSTRAINT "FK_RoomTypeServices_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES "RoomTypes" ("RoomTypeId") ON DELETE CASCADE,
        CONSTRAINT "FK_RoomTypeServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("ServiceId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    CREATE INDEX "IX_Properties_OwnerId" ON "Properties" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    CREATE INDEX "IX_RoomTypeServices_ServiceId" ON "RoomTypeServices" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    ALTER TABLE "Rooms" ADD CONSTRAINT "FK_Rooms_Properties_PropertyId" FOREIGN KEY ("PropertyId") REFERENCES "Properties" ("PropertyId") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073837_RenameKhuTroDichVuToPropertyService') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261004073837_RenameKhuTroDichVuToPropertyService', '8.0.10');
    END IF;
END $EF$;
COMMIT;

