export const routes = {
  home: "/",
  propertyDetail: "/property/sunrise-residence",
  availableRooms: "/property/sunrise-residence/rooms",
  myRoom: "/my-room",
  myContracts: "/my-contracts",
  myBills: "/my-bills",
  myBookings: "/my-bookings",
  notifications: "/notifications",
  profile: "/profile",
  managementDashboard: "/management/dashboard",
  managementAreas: "/management/areas",
  managementProperties: "/management/properties",
  managementRooms: "/management/rooms",
  managementTenants: "/management/tenants",
  managementBookings: "/management/bookings",
  managementContracts: "/management/contracts",
  managementInvoices: "/management/invoices",
  managementEquipment: "/management/equipment",
  managementMaintenance: "/management/maintenance",
  managementReports: "/management/reports",
  managementManagers: "/management/managers",
  managementUsers: "/management/users",
  login: "/login",
  register: "/register",
} as const
